"""Measure the retrieval score distribution so RELEVANCE_FLOOR is chosen, not guessed.

Embeddings + Pinecone only — no LLM calls, so this is nearly free to re-run.

Reports, split by answerable vs out-of-corpus:
  * top_score      — best cosine score returned
  * margin         — top score minus the mean of the rest (more stable than an
                     absolute cut on E5, whose scores are heavily compressed)
  * retrieval hit  — whether the expected source file appeared in top-k at all,
                     which separates *retrieval* failures from *grading* failures

Usage:
    python -m scripts.calibrate
"""
from __future__ import annotations

import json
import statistics
from datetime import datetime, timezone
from pathlib import Path

from dotenv import load_dotenv

from app.config import get_settings
from app.llm import E5Embeddings
from app.vectorstore import VectorStore

CASES_PATH = Path("eval/test_cases.json")
REPORT_PATH = Path("eval/calibration.md")


def main() -> int:
    load_dotenv()
    settings = get_settings()
    embedder = E5Embeddings(settings)
    store = VectorStore(settings)
    store.ensure_index()

    cases = json.loads(CASES_PATH.read_text(encoding="utf-8"))["cases"]

    rows = []
    for case in cases:
        matches = store.query(embedder.embed_query(case["question"]), settings.top_k)
        scores = [m["score"] for m in matches]
        top = max(scores) if scores else 0.0
        rest = sorted(scores, reverse=True)[1:]
        margin = top - (sum(rest) / len(rest)) if rest else top

        retrieved_files = [m["metadata"]["source_path"].split("/")[-1] for m in matches]
        expected = set(case["expected_sources"])
        hit = (not expected) or bool(expected & set(retrieved_files))

        rows.append(
            {
                "id": case["id"],
                "answerable": case["expected_status"] == "answered",
                "top": top,
                "margin": margin,
                "hit": hit,
                "question": case["question"],
                "top_file": retrieved_files[0] if retrieved_files else "-",
            }
        )

    print(f"{'id':>3}  {'kind':<11} {'top':>7} {'margin':>7}  {'recall':<6} top-1 file")
    print("-" * 88)
    for r in rows:
        kind = "answerable" if r["answerable"] else "out-of-corpus"
        recall = "ok" if r["hit"] else "MISS"
        print(
            f"{r['id']:>3}  {kind:<11} {r['top']:>7.4f} {r['margin']:>7.4f}  {recall:<6} {r['top_file']}"
        )

    ans = [r["top"] for r in rows if r["answerable"]]
    ooc = [r["top"] for r in rows if not r["answerable"]]
    ans_margin = [r["margin"] for r in rows if r["answerable"]]
    ooc_margin = [r["margin"] for r in rows if not r["answerable"]]

    print("\n--- top_score distribution ---")
    print(f"  answerable    n={len(ans)}  min={min(ans):.4f}  mean={statistics.mean(ans):.4f}  max={max(ans):.4f}")
    print(f"  out-of-corpus n={len(ooc)}  min={min(ooc):.4f}  mean={statistics.mean(ooc):.4f}  max={max(ooc):.4f}")
    print("\n--- margin distribution ---")
    print(f"  answerable    min={min(ans_margin):.4f}  mean={statistics.mean(ans_margin):.4f}  max={max(ans_margin):.4f}")
    print(f"  out-of-corpus min={min(ooc_margin):.4f}  mean={statistics.mean(ooc_margin):.4f}  max={max(ooc_margin):.4f}")

    misses = [r for r in rows if not r["hit"]]
    print(f"\n--- retrieval recall: {len(rows) - len(misses)}/{len(rows)} cases had an expected source in top-{settings.top_k} ---")
    for r in misses:
        print(f"  MISS case {r['id']}: {r['question']}")

    print("\n--- floor separability ---")
    separable = min(ans) > max(ooc)
    if separable:
        print(f"  CLEAN SEPARATION: any floor in ({max(ooc):.4f}, {min(ans):.4f}] splits the two sets.")
        print(f"  suggested RELEVANCE_FLOOR = {(max(ooc) + min(ans)) / 2:.4f}")
    else:
        print(f"  BANDS OVERLAP: lowest answerable ({min(ans):.4f}) <= highest out-of-corpus ({max(ooc):.4f}).")
        print("  No absolute floor can separate them. Keep the floor as a coarse backstop only")
        print("  and let the LLM grader make the real decision.")
        safe = min(ans) - 0.02
        print(f"  A floor above {min(ans):.4f} would cause FALSE REFUSALS. Safe backstop <= {safe:.4f}.")

    _write_report(rows, ans, ooc, ans_margin, ooc_margin, separable, settings)
    print(f"\n  wrote {REPORT_PATH}")
    return 0


def _write_report(rows, ans, ooc, ans_margin, ooc_margin, separable, settings) -> None:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Retrieval calibration",
        "",
        f"Generated by `python -m scripts.calibrate` on {ts}. Embeddings + Pinecone only, no LLM calls.",
        "",
        "## Why this exists",
        "",
        "`RELEVANCE_FLOOR` decides when the graph short-circuits to a refusal without",
        "spending a grader call. Picking it by guesswork would either cause false refusals",
        "or let obvious garbage through, so it is measured here instead.",
        "",
        "## Per-case scores",
        "",
        "| # | kind | top_score | margin | expected source in top-k | top-1 file |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        kind = "answerable" if r["answerable"] else "out-of-corpus"
        lines.append(
            f"| {r['id']} | {kind} | {r['top']:.4f} | {r['margin']:.4f} | "
            f"{'yes' if r['hit'] else '**MISS**'} | {r['top_file']} |"
        )

    lines += [
        "",
        "## Distribution",
        "",
        "| set | n | min | mean | max |",
        "|---|---|---|---|---|",
        f"| answerable `top_score` | {len(ans)} | {min(ans):.4f} | {statistics.mean(ans):.4f} | {max(ans):.4f} |",
        f"| out-of-corpus `top_score` | {len(ooc)} | {min(ooc):.4f} | {statistics.mean(ooc):.4f} | {max(ooc):.4f} |",
        f"| answerable `margin` | {len(ans_margin)} | {min(ans_margin):.4f} | {statistics.mean(ans_margin):.4f} | {max(ans_margin):.4f} |",
        f"| out-of-corpus `margin` | {len(ooc_margin)} | {min(ooc_margin):.4f} | {statistics.mean(ooc_margin):.4f} | {max(ooc_margin):.4f} |",
        "",
        "## Conclusion",
        "",
    ]
    if separable:
        lines.append(
            f"The two sets separate cleanly; a floor of "
            f"{(max(ooc) + min(ans)) / 2:.4f} splits them."
        )
    else:
        lines += [
            f"**The bands overlap.** The lowest answerable question scores {min(ans):.4f}, "
            f"while the highest out-of-corpus question scores {max(ooc):.4f} — the "
            "out-of-corpus set sits *inside* the answerable range. This is the E5 score "
            "compression the design anticipated: on a corpus this small every chunk is "
            "somewhat similar to every query.",
            "",
            "**No absolute threshold can separate answerable from unanswerable questions "
            "here.** Any floor high enough to catch the out-of-corpus cases would also "
            f"refuse legitimate questions (anything above {min(ans):.4f} causes false refusals).",
            "",
            f"Margins overlap too (answerable {min(ans_margin):.4f}–{max(ans_margin):.4f} vs "
            f"out-of-corpus {min(ooc_margin):.4f}–{max(ooc_margin):.4f}), so a relative "
            "margin test does not rescue it either.",
            "",
            f"**Decision: `RELEVANCE_FLOOR` stays at {settings.relevance_floor}** — deliberately "
            f"well below the observed answerable minimum ({min(ans):.4f}) so it can never "
            "cause a false refusal. It is a coarse backstop for genuinely degenerate "
            "retrieval (empty index, wrong-language query), *not* the relevance decision. "
            "The LLM grader in `grade_context` makes the real judgement, and the "
            "out-of-corpus eval cases are what verify it.",
            "",
            "Retrieval recall is "
            f"{sum(1 for r in rows if r['hit'])}/{len(rows)} — the correct source is "
            "essentially always retrieved, which confirms failures are grading failures, "
            "not retrieval failures.",
        ]

    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
